name: Build Live ISO

on:
  workflow_dispatch:
    inputs:
      platform:
        required: true
        type: choice
        options:
          - amd64
          - arm64
  pull_request:
    branches:
      - main

env:
  IMAGE_NAME: ${{ github.event.repository.name }}
  IMAGE_REGISTRY: "ghcr.io/${{ github.repository_owner }}"
  DEFAULT_TAG: "latest"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build-iso:
    runs-on: ubuntu-24.04

    steps:
      - uses: ublue-os/remove-unwanted-software@v9

      - uses: actions/checkout@v4

      - name: Build ISO
        id: build
        uses: RakuOS/titanoboa@main
        with:
          image-ref: ghcr.io/rakuos/rakuos-kde:latest
          hook-post-rootfs: ${{ github.workspace }}/config/configure-iso.sh
          hook-pre-initramfs: ${{ github.workspace }}/config/pre_initramfs.sh
          compression: squashfs
          builder-distro: fedora

      - name: Rename and Checksum ISO
        run: |
          BUILD_DATE=$(date -u +%Y.%m.%d)
          mkdir -p output
          mv ${{ steps.build.outputs.iso-dest }} output/rakuos-kde-${BUILD_DATE}-${{ inputs.platform }}.iso
          (cd output && sha256sum rakuos-kde-${BUILD_DATE}-${{ inputs.platform }}.iso | tee rakuos-kde-${BUILD_DATE}-${{ inputs.platform }}.iso-CHECKSUM)

      # 📦 Upload artifacts to GitHub
      - name: Upload ISO
        uses: actions/upload-artifact@v4
        with:
          name: custom-iso
          path: output/


